#!/usr/bin/env python3
#
# An implementation of binary search in python where the input is a sorted list
# of integers.
#
from typing import List

def binary_search(input: List[int], target: int) -> int:
    """
    Returns the index at which the first occurence of the given *target* occurs
    in a sorted *input*. Returns -1 if *target* is not in the given *input*.

    >>> binary_search([1,2,3], 1)
    0

    >>> binary_search([1,5,20,99], 0)
    -1

    >>> binary_search([1,5,20,99], 99)
    3

    >>> binary_search([1,5,6,20,99], 6)
    2
    """
    start = 0
    end = len(input) - 1

    while start <= end:
        mid = (start + end) // 2
        if input[mid] < target:
            start = mid + 1

        elif input[mid] > target:
            end = mid - 1

        else:
            return mid

    return -1


if __name__ == "__main__":
    import doctest
    doctest.testmod()
